
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ExecuteSQLCommandsParameters {
    /**
    * Label: PostgreSQL server, type: entry
    */
    String server
    /**
    * Label: PostgreSQL port, type: entry
    */
    String port
    /**
    * Label: Database credentials, type: credential
    */
    String credential
    /**
    * Label: Database name, type: entry
    */
    String database
    /**
    * Label: SQL query, type: textarea
    */
    String sql_query

    static ExecuteSQLCommandsParameters initParameters(StepParameters sp) {
        ExecuteSQLCommandsParameters parameters = new ExecuteSQLCommandsParameters()

        def server = sp.getRequiredParameter('server').value
        parameters.server = server
        def port = sp.getRequiredParameter('port').value
        parameters.port = port
        def credential = sp.getRequiredParameter('credential').value
        parameters.credential = credential
        def database = sp.getRequiredParameter('database').value
        parameters.database = database
        def sql_query = sp.getRequiredParameter('sql_query').value
        parameters.sql_query = sql_query

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: fc069667d2c5f617ed6b3e26fd1d2fd3 ===
